# apache with htaccess auth
# docker run --rm -d -t -i -p 80:80 -p 443:443  -v /storage/Docker/html:/var/www/html --restart=always  --name=apache-htaccess-auth  mrunal4/apache-htaccess-auth:latest 
# Access via "http://localhost:80" (or "http://$(docker-machine ip):8080" if using docker-machine)
#

version: '2'

services:

  # Create apache-htaccess-auth container
  apache-htaccess-auth:
    image: mrunal4/apache-htaccess-auth:latest
    container_name: apache-htaccess-auth
    restart: always
    environment:
      - TERM=xterm
    hostname: 'apache-htaccess-auth'
  #    domainname: 'mz1' # Change to the hostname you will use
    ports:
      - "80:80"             #http
      - "443:443"           #https
      
    volumes:
      # requires proper authorizations, see rights (incase of 403-forbidden error on web browser, please check /data/media permissions)
      - /storage/Docker/html:/var/www/html
      - ./000-default.conf:/etc/apache2/sites-enabled/000-default.conf 
      - ./.htpasswd:/etc/apache2/.htpasswd 
      - ./create-htaccess-users.sh /root/create-htaccess-users.sh
      - ./create_users.csv /root/create_users.csv
